### ISSUE TITLE
cannot mark with 'choice' and correct header info

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh-app#14]
In XML line 46024 the subheading 'secondary sources' is not in print version in bigger font and hence not marked as subheading in XML. Formatting this with 'choice' causes problems. I left it as is, and we need to sort this. #

**Comment by wsalesky** [comment]
@dlschwartz How about this one, can it be closed? It would be nice to clean the list up.

**Comment by wsalesky** [comment]
@dlschwartz Just a reminder about this one. Can it be closed?

**Comment by dlschwartz** [comment]
yes, thanks
