### ISSUE TITLE
Revisions to e-GEDSH front and back

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh-app#17]
@wsalesky  I have made major revisions to the front and back of e-GEDSH. In short, I have taken each of the items in the Table of Contents of the print edition and treated them like an entry. This should allow linking to these entities from elsewhere and allow for them each to appear on a separate page.

For the major (left-adjusted) sections, I have wrapped them in a div type="section" and added an ab element with idno, milestone, and note (type="front" for front matter and "back" for backmatter).

For the indented subsections I have put each inside of a div type="subsection" and added an ab element as above.

For even lower subsections I have put each inside of a div type="subSubsection" but I have not included an ab element and have not assigned idnos, etc. Users will find and view these through the div type="subsection" of which they are a part.

There are a variety of uses I could imagine using to put this encoding to work for visualizing the text. I'll start with my ideal, even though I'm not sure it's feasible. Can we include the "Front Matter" and "Back Matter" as options before and after the alphabet on the browse page such that when a user clicked on either they saw a list with links to the relevant page. For "Front Matter" this would include everything with a Roman numeral on the Table of Contents. For "Back Matter" it would include everything from pp. 451-535 in the Table of Contents. It would also be nice to have similar features for "Front Matter" and "Back Matter" at the end of the left-hand alphabetical listing that the user sees when viewing an article.

Please let me know if you have any questions of if I need to adjust any of the encoding in order to make possible what I would like. And, of course, if the hope of adding front and back as bookends to an alphabetical list is too difficult/impossible, please don't hesitate to say. Thank you Winona!

**Comment by wsalesky** [comment]
@dlschwartz working on this today. 

Have implemented paging, next up, adding front/back matter to the ABC browse. 

Example of paging: 
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Making-GEDSH-print

You can still access the full front/back via: 
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=front

**Comment by dlschwartz** [comment]
Sorry @wsalesky, I've been meaning to raise the issue of page numbers. I put those in very early on when I transcribed the front and back matter. At the time, I thought we were going to insert pb elements throughout the text. @davidamichelson subsequently expressed a strong preference for inserting milestone elements for each entry that would include the pages on which the entry appeared even if it did not include the specific page breaks. In a way, these pb elements are a legacy of my early encoding and for the sake of consistency, probably ought to be removed. 

In fact, I have added milestone elements to the sections in the front and back matter to make those consistent with the entries. If we simply visualized each of these sections as a single webpage (I've assigned each a URI) then we could put the footnotes (when relevant) at the bottom of that webpage. 

How does this sound to you? Should I go ahead and remove the pb elements and just use milestone elements throughout?

**Comment by wsalesky** [comment]
@dlschwartz I think that is fine. It may already work as expected. If not let me know and I will make adjustments.

**Comment by wsalesky** [comment]
Added front/back matter to browse: 
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/browse.html

**Comment by dlschwartz** [comment]
Excellent! Thanks.

**Comment by dlschwartz** [comment]
@wsalesky I have further revised front and back to remove note type to indicate front and back and replace it with idno type="front" or idno type="back" with text node ordering the elements of the front and back matter. https://github.com/srophe/e-gedsh/commit/0c5c78d7489053aba347b8dc3b0283d7edf69de6

**Comment by wsalesky** [comment]
I think this has been resolved.

**Comment by dlschwartz** [comment]
Agreed. I think the major issues with my changes to the TEI have been sorted. There are a few additional issues that have popped up but I think it might be good to discuss on Wednesday and then create specific issues for those. Thank you! Things are looking great.
