### ISSUE TITLE
How to Cite This Page feature

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh-app#20]
"How to Cite This Page"
What I have written up here should work to add this feature to e-GEDSH just like it appears on Syriaca.org. We would like this to appear on each page which should mean every div type="section", div type="subsection", and div type="entry". But, not all pages will contain all bibliographic elements. Hopefully it is possible to simply include them when present and leave them off when not.  At the bottom I've put an xpath for locating the entity in brackets. Thanks @wsalesky and please let me know if you have any questions.

Short (to appear at the bottom of every page):
[author], "[head]," in [work], edited by, [editor 1], [editor 2], [editor 3], and [editor 4], last modified [date], [idno].

Bibliography (to show when "Show full citation information" is selected):
[author]. "[head]." In [work]. Edited by, [editor 1], [editor 2], [editor 3], and [editor 4]. Digitized by [e-editor 1], [e-editor 2], [e-editor 3], and [e-editor 4]. Last modified [date]. [idno].

About This Entry
Authorial Responsibility: [author]
Editorial Responsibility: [editor 1], [editor 2], [editor 3], [editor 4]
Additional Credit: /TEI/teiHeader/fileDesc/titleStmt/respStmt[all]

author: /TEI/text/front/div[relative]/byline/persName (if two, connect with "and", if multiple string them together with commas and "and")
head: /TEI/text/front/div[relative]/head
title: /TEI/teiHeader/fileDesc/titleStmt/title
editor 1: /TEI/teiHeader/fileDesc/sourceDesc/biblStruct/monogr/editor[1]
editor 2: /TEI/teiHeader/fileDesc/sourceDesc/biblStruct/monogr/editor[2]
editor 3: /TEI/teiHeader/fileDesc/sourceDesc/biblStruct/monogr/editor[3]
editor 4: /TEI/teiHeader/fileDesc/sourceDesc/biblStruct/monogr/editor[4]
e-editor 1: /TEI/teiHeader/fileDesc/titleStmt/respStmt[1]/name[1]
e-editor 2: /TEI/teiHeader/fileDesc/titleStmt/respStmt[2]/name[2]
e-editor 3: /TEI/teiHeader/fileDesc/titleStmt/respStmt[3]/name[3]
e-editor 4: /TEI/teiHeader/fileDesc/titleStmt/respStmt[4]/name[4]
date (only include day, month, year): /TEI/teiHeader/fileDesc/publicationStmt/date
idno: //div[relative]/ab/idno type="URI"

**Comment by wsalesky** [comment]
@dlschwartz How does this look: 
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Aba-II-of-Kashkar

**Comment by dlschwartz** [comment]
I think this looks great! I can show this to Syriaca folks tomorrow and get their feedback and then I'll share it with the print editors to get their feedback.

**Comment by dlschwartz** [comment]
@wsalesky I just noticed a problem. The head elements in the div type="bibl" ("Primary Sources" and "Secondary Sources") are getting pulled into the bibliographic entry. Could we exclude heads in div type="bibl"? 

Ex: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Abdisho-bar-Bahriz

Thanks

**Comment by dlschwartz** [comment]
@wsalesky In addition to the problem with Primary and Secondary showing up in the citation, which happens in many entries, there is also a problem with the List of Patriarchs section. 

Scroll to the bottom here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/List-of-Patriarchs-Churches-Middle-East. It is pulling in every head contained with the div. In this it should only pull in the child of head type="section" and not the children of head type="subsection" or head type="subSubsection".

I think that will sort out the problem but please let me know if I need to change something. Thanks.

**Comment by wsalesky** [comment]
Resolved.

**Comment by dlschwartz** [comment]
This looks great @wsalesky. I have a question out to Ute that may result in a change but I like this the way it it. Thanks.
