### ISSUE TITLE
webhooks

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh-app#21]
@wsalesky I'm sorry to say it, but I've just made some changes to the back that aren't showing up. If you want to send me an email with directions to address this myself, I'm happy to try again. In your last attempt, I didn't seem to have the necessary permissions. Thanks.

**Comment by wsalesky** [comment]
It says it updated. What are you not seeing?

**Comment by dlschwartz** [comment]
This commit https://github.com/srophe/e-gedsh/commit/deefa1e5bf3ef3f5631dd75a89a32ea81caf058f doesn't show up. Any maybe the two I pushed before that. They weren't supposed to change anything in the html though so it's hard to say. Thanks.

**Comment by wsalesky** [comment]
I added it manually. I'm not sure what happened since the webhooks claim to have worked correctly. Let me know if you have problems in the future.
