### ISSUE TITLE
Notes showing up twice in List of Patriarchs

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh-app#22]
@wsalesky http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/List-of-Patriarchs-Churches-Middle-East

The notes show up twice. You might need to play around a bit with clicking on the links for the notes to see what I'm talking about. I think they are showing up both at the end of the div in which they appear and at the end of the div containing the List of Patriarchs overall. At first I thought this had something to do with the pb elements but I think it's the nesting of the divs that is to blame.

**Comment by dlschwartz** [comment]
The easiest place to see this problem is to follow the link and scroll all the way to the bottom where you will see footnotes 12 and 13 follow the div type="subsection" and then all 13 footnotes for the entire div type="section" appear again. The best solution I think would be to have the footnotes show up only at the end of each div type="subsection".

**Comment by wsalesky** [comment]
Resolved

**Comment by dlschwartz** [comment]
Thanks @wsalesky!
