### ISSUE TITLE
Delete "Author" 

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh-app#24]
@wsalesky Right now, the app adds an "Author: " before names wrapped in the byline element. Whether in the front / back matter or the entries, the consensus is that the name indicates authorship clearly enough. It would be great if we could simply remove those. Thanks.

**Comment by dlschwartz** [comment]
This is the same issue as https://github.com/srophe/e-gedsh/issues/146, which I will close.

**Comment by wsalesky** [comment]
Done
