### ISSUE TITLE
Patriarch list, Maronite

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh-app#25]
@wsalesky I noticed I was getting odd results when I would click on the link to the subsection of the Patriarch list for the Maronite church. It turns out that the URI I had assigned to that div type=subsection was the same as the URI for the entry on the Maronite Church. I changed the URI in the patriarch list but now the link in browse just takes users to the entry on the Maronite Church. Here's the commit: https://github.com/srophe/e-gedsh/commit/a1852149d07e7dd699b64f7b38751478ab27a3ce. Thanks.

**Comment by wsalesky** [comment]
So it does not take the users to the subsection?

**Comment by dlschwartz** [comment]
I should have grabbed a screenshot before I changed the TEI. Before the change, clicking on that link in the browse brought up the entry for "Maronite Church" followed immediately by the whole div type="section" that contains the Maronite Church div type="subsection". 

In fact, all of the browse links to div type="subsection" take the user to the parent div type="section". I started to create an issue about this problem but deleted it because I'm not sure exactly what approach I want to take to solve it. I think I should ask the editors what their expectations would be. Would they like to be taken to a page containing only the subsection, or, would they like to be taken to a page containing the whole div type="section" but with the scroll adjusted to the selected div type="subsection." I put this on the agenda for Tuesday.

**Comment by wsalesky** [comment]
I will hold off until Tuesday then.

**Comment by dlschwartz** [comment]
We didn't discuss this in today's meeting. This should be pretty straightforward though. I had to change the URI for the div type="subsection" on this subsection because it had already been used for the related encyclopedia entry. The links in the browse just need to be changed to reflect the new URI. Thanks.

**Comment by wsalesky** [comment]
Fixed.
