### ISSUE TITLE
Linked Data for GEDSH headwords

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh-app#26]
@wsalesky, we seem to have lost the linked data associated with the GEDSH headwords. They all show blank even though there is linked data associated with other syriaca headwords, for example http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Antioch. Thanks!

**Comment by wsalesky** [comment]
Sorry, somehow I commit code pointing to my local install not the dev server! It is fixed now.

**Comment by dlschwartz** [comment]
Thank you
