### ISSUE TITLE
URLs from left side browse bar

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh-app#27]
@wsalesky, when use the browse bar on the left side of the screen, it takes me to the entry but has a URL different from the norm: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Aba-II-of-Kashkar?fq=;fq-Browse:Browse;A; instead of http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Aba-II-of-Kashkar. Is this to be expected? Thanks.

**Comment by wsalesky** [comment]
Yes, this just keeps the browse menu open to the current letter when you navigate. 
If you remove the '?fq=;fq-Browse:Browse;A;'  the only effect is that the 'A' menu will be closed.

**Comment by dlschwartz** [comment]
Ah, got it. I wasn't sure if something else was going on there. Thanks.
