### ISSUE TITLE
Footnotes not appearing

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh-app#29]
The footnote numbers appear in the body of the text and they have hyperlinks. However, those links do not go anywhere and the text of the footnotes appears nowhere on the page. There are no footnotes in the articles, just in the front and back matter.

Ex.: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Syriac-Orthodox-Uniate-Continuations

**Comment by wsalesky** [comment]
fixed.
