### ISSUE TITLE
TEI/XML button not working in front and back matter

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh-app#30]
The TEI/XML buttons work find in the main articles but do not seem to work anywhere in the front and back sections.

Ex.: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Syriac-Orthodox-Uniate-Continuations

**Comment by wsalesky** [comment]
Fixed.

**Comment by wsalesky** [comment]
Added to incorrect issue.

**Comment by wsalesky** [comment]
This works on my local install. Dev is down again, when it is back up I will test on Dev.

**Comment by wsalesky** [comment]
Fixed on dev.
