### ISSUE TITLE
Webhooks?

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh-app#31]
@wsalesky I noticed a problem with the LOD box in the "Antioch" article. The names of several entities with their links to Syriaca.org were not appearing. I checked the TEI and found that the script you ran to insert Syriaca.org URIs worked perfectly (which is great news!). However, it resulted in double persName and placeName elements in instances where I had manually added these earlier. I removed the duplicates and pushed to GitHub but the webhooks don't seem to be working. Thanks.

**Comment by wsalesky** [comment]
I've turned them off while I troubleshoot why the dev server keeps crashing. I will manually load the changes. Hope to be migrating to a new version soon.

**Comment by dlschwartz** [comment]
Very good. Thanks Winona.
