### ISSUE TITLE
The Linked Data Box is not expanding to show all of its links (or perhaps is incompletely collecting URIs)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh-app#38]
I am guessing this is a breakage of the interface related to the new data structure: https://github.com/srophe/e-gedsh/issues/268

Clicking the "show other resources" button does not change the box.

**Comment by dlschwartz** [comment]
@wsalesky, is this the ongoing SPARQL issue you mentioned? This box is blank in SPEAR.

**Comment by wsalesky** [comment]
Yes.

**Comment by wsalesky** [comment]
This is fixed. Same as here: https://github.com/srophe/srophe-eXist-app/issues/1231
Code on server out of sync with github branch .

**Comment by davidamichelson** [comment]
Thank you!

**Comment by dlschwartz** [comment]
@wsalesky it looks like this problem has returned: https://gedsh.bethmardutho.org/Edessa. Thank you.

**Comment by wsalesky** [comment]
@dlschwartz This is not a code issue, it is a dev server issue. The dev server seems to be down. I'm looking into alternative triplestores so we can move our RDF to a more stable environment when we move the applications. Still experimenting, but I think I have a good alternative.

**Comment by dlschwartz** [comment]
Great, thanks Winona.
