### ISSUE TITLE
Error in "How to Cite This Entry"

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh-app#39]
@wsalesky George Kiraz noticed that the "how to cite" section in eGEDSH is incorrectly constructing the citation. It looks like the headword is being grabbed twice. If I understand correctly, the bibliography should be constructed using the tei:seriesStmt as the work in which the entry is contained. See George's screen shot below. What he's highlighted in yellow should instead come from `<title level="m">Gorgias Encyclopedic Dictionary of the Syriac Heritage: Electronic Edition</title>` in tei:seriesStmt.

![image](https://user-images.githubusercontent.com/4984270/133626400-e47e95a3-1f7b-45c6-8eb0-88b9b2f02207.png)

Thanks Winona!

**Comment by wsalesky** [comment]
What record is this? Link?

**Comment by dlschwartz** [comment]
The record pictured is https://gedsh.bethmardutho.org/entry/Beth-Qatraye. FYI, all of the records are doing the same thing here. Thanks Winona.

**Comment by wsalesky** [comment]
Fixed!
