### ISSUE TITLE
Cross-references

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh-app#6]
@wsalesky We would like to visualize the cross-references in the left hand column along with the articles. These are encoded as div type="crossreference". We would like these alphabetized together with the entries (encoded with kiv type="entry"). I hope it will not present a difficulty to do that. 

Also, we would like the head and abstract to appear in the center column.  There are two types of these. 1) At line 2591 there is an actual cross-reference and we would like that link to work of course. 2) At line 24338 there is no actual link but rather a suggestion about where a user would look to find what they are looking for. In this case we just want the English text to render.

Thanks @wsalesky

**Comment by wsalesky** [comment]
@dlschwartz 
In the browse page the cross refs are visualized with a link to the 'see also'
See the 4th entry:
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/browse.html

Can we clarify how you want these to function in the left menu on an entry page?
ex:
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?fq=;fq-Browse:A&id=http://gedsh.bethmardutho.org/Aba-I

Should they link the the referenced entry? Or do you want to take the user to a page with the cross ref head and a text entry redirecting them to the see also? If we want this second approach we will need to give all the cross refs an idno.

**Comment by dlschwartz** [comment]
@wsalesky, I think we discussed this yesterday. Do you have any additional questions on this issue?

**Comment by wsalesky** [comment]
No I think this has been resolved as of last night. If you can just review the browse options to make sure you approve. If so you can close this.

**Comment by dlschwartz** [comment]
I think that the only thing remaining from our discussion yesterday was to place a hyperlink on Isaiah of Scetis in this context: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/browse.html. Otherwise, I think you have taken care of everything we discussed. It looks great, thanks!

**Comment by wsalesky** [comment]
The link should be there, try a hard refresh of the page.

**Comment by dlschwartz** [comment]
That did it. Thanks Winona! I'll close this out then.
