### ISSUE TITLE
RDF Box: (Was "Syriaca links in right column")

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh-app#7]
@wsalesky, at the moment, we have Syriaca.org URIs for persons and places that we would like to visualize in the right hand column. (Eventually we hope to have work and manuscript URIs as well but at the moment we do not.) 

We are a bit concerned about cluttering things up though. We are thinking that it might be nice to use drop downs. The box could be labeled "Links to Syriaca.org" and then whenever person and/or place URIs are present, there would be an option to select a drop down that would be labeled:
"Syriaca.org has information on # related person/persons"
"Syriaca.org has information on # related place/places"

Now that I've described this, I'm not sure what would show when someone selected the drop down option. Is it feasible to grab the record title and URI from Syriaca.org and display it here for the user to select if they want to follow a link to Syriaca.org? All we would need is what the clipboard icon your recently created selects. Can we do that with relative ease and stability?

Please feel free to play around with this. I'm more interested in having something that looks good and is user-friendly than I am in having something that adheres really closely to what I've described here. Your design skill clearly exceed mine! Thanks Winona.

**Comment by wsalesky** [comment]
@dlschwartz What do these person and place references look like. I see some like this:
`<idno type="subject">http://syriaca.org/person/307</idno>`

Are there also refs in the body of the text?

**Comment by wsalesky** [comment]
Note to self:
Included in this will be persName/placeName with ref attributes.

**Comment by wsalesky** [comment]
Example:
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Abdisho-of-Gazarta&num=6

**Comment by dlschwartz** [comment]
This is a great start. I think we should discuss this further as a group on Tuesday and then get back to you in our meeting on Wednesday. Thanks.

**Comment by davidamichelson** [comment]
@wsalesky I will try to summarize the changes we would like. We can review tomorrow:

Please change the name of the box from 
"Links to Syriaca.org" to "Additional External Resources"

Please include a "?" tooltip on "Additional External Resources" which pops up this message “This sidebar provides links via Syriaca.org to additional resources beyond those mentioned by the author of this entry.”

Then format the contents of the box this way:

Topics Related to this Entry:
- ʿAbdishoʿ of Gazarta - ܥܒܕܝܫܘܥ ܕܓܙܪܬܐ (11 links) >
- Mar Aḥa - [ Syriac Not Available ] (5 links) >
- Gazarta - [ Syriac Not Available ] (1 link) >

Notes to this visualization:
The list of topics is generated from the egesdh record and should be listed in this order:
1. The first topic should always be the one found at path div type="entry"/ab type="idnos"/idno type="subject"
2. The other topics should be drawn from the record, but then listed in alphabetical order by Syriaca.org "en" headword

*Please get rid of the labels person, place, etc. 
*Also please note that we will not list the Syriaca.org URIs.
*The names should be generated from Syriaca.org headwords, En and Syr.
*The font should be Estrangelo Edessa for all Syr names.
*The number for the links should be auto generated using the following script: In the Syriaca.org record, count the number of tei:IDNO plus tei:bibl where the IDNO is part of the text node and the  bibl is part of the sources for the record. For bibl, this can be determined by it's having an xml:id of the type "bib[URINumber]-[0-9]+)" or by the path for each record type. For persons this would be TEI/text/body/listPerson/person/bibl and TEI/text/body/listPerson/person/IDNO
*Clicking on the main text of any of these topics should take one to the Syriaca.org entry
*Clicking on the part that says (X links) or the dropdown arrow should produce a collapsed list, see below.

When expanded each topic should display a list indented below the topic as in this example:
[Note let's discuss this before you start to implement it!!!]

Topics Related to this Entry:
- ʿAbdishoʿ of Gazarta - ܥܒܕܝܫܘܥ ܕܓܙܪܬܐ (11 links) V
 -Syriaca.org: http://syriaca.org/person/311
 -"Abdisho of Gazarta" in the Comprehensive Bibliography on Syriac Christianity
 -VIAF 
 -9 Bibliographic items (see list).
- Mar Aḥa - [ Syriac Not Available ] (5 links) >
- Gazarta - [ Syriac Not Available ] (1 link) >

Notes:
This list is auto generated from the the Syriaca.org record. 
Its order is listing all the IDNOs from TEI/text/body/listPerson/person/IDNO but with the caveat that Wikipedia entries should be excluded.
Each sublink should be a live link. 
The bibliographic items link should link to: #bib[URINumber]-1 of the Syriaca.org HTML record to show the sources list.
The count on the bibliographic items should be taken from the count done above.

**Comment by davidamichelson** [comment]
@dlschwartz We should think about the labeling and features here more with Winona. Maybe the dropdown is too much?

We could change "Topics Related to this Entry:" to "Linked Data for this Entry:"

Also, should we include a label for URIs at the bottom of this box? I do think we have a duty to teach users about URIs since they are key to Syriaca.org and the Corpus too.

The bottom of the box could read:

Identifiers for this Entry:
URI for this entry as a webpage: http://gedsh.bethmardutho.org/Abdisho-of-Gazarta
URI for this entry as a citation: http://syriaca.org/bibl/15
URI for the subject of this entry: http://syriaca.org/person/311

**Comment by davidamichelson** [comment]
The more I think about this the more I realize that we need to get this right and do it well. Let's talk more, this feature is at the core of Syriaca.org and we need to do it well.

**Comment by davidamichelson** [comment]
I had a vision about this and I think I have a workable idea. Jotting some notes here. The box should offer two main points of data on 1. Related Resources and 2. Related Topics

Here is a possible model:

Syriaca.org has Linked Open Data related to the topic of this article:
32 related resources >
7 related topics >

When expanded it would read:


Syriaca.org has Linked Open Data related to the topic of this article:
32 related resources v
- 12 related links (URIS or URLS)
- 20 related bibliographic items
7 related topics v
- 2 related places
- 4 related persons
- 1 related manuscript

clicking on these could expand further but probably should just take the user to the related page perhaps with an anchor to the IDNOS, the bibls, the related sections.

**Comment by davidamichelson** [comment]
The RDF/TEI sources for this would be:


    32 related resources v = IDNOs + Syriaca.org bibl URIS
    -- 12 related links (3 URIS and 9 other URLS)
Eventually theses related links could be broken down into URIS (which would be few) and URLS which could include any web resources such as the count of SPEAR entries which reference a URI
    -- 20 related bibliographic items = Syriaca.org bible URIs
    7 related topics v = Syriaca.org URIS except bibls
    -- 2 related places
    -- 4 related persons
    -- 1 related manuscript

**Comment by davidamichelson** [comment]
@wsalesky Let's discuss this tomorrow (3/15):

Here is what we want for external modules (at present: egedsh and the corpus and probably SPEAR):

On the app side, the app for egedsh should gather up all Syriaca.org URIs in the particular XML entry (a single encyclopedia entry). 

It should group the Syriaca.org URIS in two ways: 
1. Main entry
thus for the e-gedsh entry which has idno type="URI" http://gedsh.bethmardutho.org/Aba-I the main entry URI would be  idno type="subject" http://syriaca.org/person/306
2. Others
this would be to grab any other Syriac.org URIS in the entry except http://syriaca.org/person/306

Then the app should send these to our RDF API

The results should be then be processed and displayed by the e-gedsh app in a right hand RDF box as follows (numbers are made up):

Syriaca.org has Linked Data related this article:

Resources related to "Aba I" 
    32 related resources >
    7 related topics >

Resources related to other topics in this article:
    478 related resources & 85 related topics >

Notes:
The label "Aba I" should be generated by the app from it's body/div type="entry"/head, not from the Syriaca.org headword.
The label "Aba I" should be a live link to http://syriaca.org/person/306
The two sections correspond to the main URI and the Others.

When expanded the Main Enry part of box would read:

Syriaca.org has Linked Data related to this article:
Resources related to "Aba I" 
    32 related resources v
    -- 12 related links (URIS or URLS)
    -- 20 related bibliographic items
    7 related topics v
    -- 2 related places
    -- 4 related persons
    -- 1 related manuscript

I need to work with you write the SPARQL query generate these

When expanded the Others part of box would be modeled after the collapsed main entry part:

Resources related to other topics in this article:
     478 related resources & 85 related topics v
       "Edessa" 
             95 related resources >
             32 related topics >
       "School of Nisibis"
             45 related resources >
             11 related topics >
   
Notes:

These URLS would take their labels from the XML nodes in e-gedsh
They would need the script to de-duplicate the Syriac.org URIs and to order by alphabetical (I think)

**Comment by dlschwartz** [comment]
@davidamichelson and @wsalesky, I just added a number of placeName and persName elements to the GEDSH entry for Antioch. These should help for testing purposes. I believe I added 15 syriaca URIs. I skipped GEDSH headwords because they are already wrapped in ref elements and the schema currently does not allow values outside of GEDSH headwords. We'll have to add that later. Please let me know if you encounter problems or questions. Thanks Winona!

**Comment by davidamichelson** [comment]
@wsalesky Okay one more simplified try at this! Disregard above.

On the app side, the app for egedsh should gather up all Syriaca.org URIs in the particular XML entry (a single encyclopedia entry). It should group the Syriaca.org URIS in two ways:

1. Main entry: the e-gedsh entry which has idno type="URI" http://gedsh.bethmardutho.org/Aba-I the main entry URI would be idno type="subject" http://syriaca.org/person/306
2. Others: any other Syriac.org URIS in the entry except http://syriaca.org/person/306

Then the app should send these to our RDF API and get back two counts for each Syriaca.org URI submitted:
1. "Citations" = Count of non-Syriaca.org IDNOs have a near match plus how many Syriaca.org Bibl URIs (deduplicated) have a relationship to the Syriaca.org URI
2. "Subjects" = Count of Syriaca.org URIS (excluding bibl URIS, and deduplicated) have any relationship to the submitted Syriaca.org URI

The results should be then be processed and displayed by the e-gedsh app in a right hand RDF box as follows (numbers are made up):

Syriaca.org has Linked Data related this article:

Resources related to "Aba I"
- 32 related citations
- 7 related subjects

Resources related to X other subjects mentioned in this article. Show...

Notes:
The label "Aba I" should be generated by the app from it's body/div type="entry"/head, not from the Syriaca.org headword.
The label "Aba I" should be a live link to http://syriaca.org/person/306
The whole first section will not expand, but clicking anywhere on it should open http://syriaca.org/person/306

When the second section expanded by "Show..." the it would list all other Syriaca.org entities mentioned in the article. The "labels" should be taken from the textnode of the entry GEDSH XML document with the ref pointing to Syriaca.org not from Syriaca.org's headwords

Syriaca.org has Linked Data related this article:

Resources related to "Aba I"
- 32 related citations
- 7 related subjects

Resources related to X other subjects mentioned in this article. Hide...
"Edessa"
- 95 related citations
- 32 related subjects
"School of Nisibis"
- 45 related citations
- 11 related subjects

Notes:
These URLS would take their labels from the XML nodes in e-gedsh
They would need the script to de-duplicate the Syriac.org URIs and to order by alphabetical
They would be generated and formatted the same way as the list for Aba I

**Comment by davidamichelson** [comment]
Could we get a mock up of this by the 23rd?

**Comment by wsalesky** [comment]
Mockup is in place for tomorrow's demo. Numbers in under the "show/hide" div are fake in the interest of speeding up load time.

**Comment by davidamichelson** [comment]
It worked fabulously, thanks!

**Comment by wsalesky** [comment]
I think this has been resolved? @dlschwartz @davidamichelson if you agree one of you may close it.

**Comment by wsalesky** [comment]
@dlschwartz Can we close this?

**Comment by dlschwartz** [comment]
Yes, thanks!
