### ISSUE TITLE
Update styles

### ISSUE THREAD

**Issue by wsalesky** [srophe/e-gedsh-app#9]
Updated branding. 
Add banner image and change color scheme.

**Comment by wsalesky** [comment]
@dlschwartz Here is the first attempt at a banner. Unfortunatly the image used by the book cover is very skinny, so it is difficult to get a nice 'slice' of it for such a wide banner. 

Also,  It would be nice to get some content for this home page, I think that will help with the visuals. 
Thanks!

**Comment by wsalesky** [comment]
@dlschwartz Oh, and a citation for the image used for the banner. I have used both the image from the manuscript, and the image from the back cover (to give the banner some texture).

**Comment by dlschwartz** [comment]
Clever. I like this a lot, especially the inscription in the background. Could we perhaps take a slightly higher slice of the mss image so that we get a cluster of grapes in as well? Also, if we could cut the inscription image slightly differently, I think it would be good to see more of the the dark stone with the inscription. Right now, I see a lot of the white un-inscribed stone and I want more inscription.  This looks great though! Well done handling a tricky image.

**Comment by dlschwartz** [comment]
Also, I think we want "e-GEDSH" rather than "E-Gedsh". George may have a different opinion but this is an electronic version of the Gorgias Encyclopedic Dictionary of the Syriac Heritage.

**Comment by dlschwartz** [comment]
Logos for the bottom of the page should include (as on the Syriaca.org homepage): Balzan, Beth Mardutho, Gorgias Press (https://ivospubniche.blob.core.windows.net/accounts/0011857.png), IDHMC, Vanderbilt.

**Comment by dlschwartz** [comment]
Inscription: Syriac inscription in ʿArdnas, Ṭur ʿAbdin. See Fig 123c. Photo: Helen Brock (1985).

Mss: Ms. Paris, Bibliothèque Nationale, Syr. 341, f. 143r. ©Bibliothèque Nationale de France.

**Comment by dlschwartz** [comment]
I suppose we should add <ref target="http://gedsh.bethmardutho.org/fig/123c">Fig. 123c</ref>

**Comment by dlschwartz** [comment]
I suppose we should add `<ref target="http://gedsh.bethmardutho.org/fig/123c">Fig. 123c</ref>`

**Comment by dlschwartz** [comment]
@wsalesky The text for "What is e-GEDSH?" is something Ute and I will need to write up. 

We will also want to have links on this page to some text from the front matter of the print edition: "The Making of the Gorgias Encyclopedic Dictionary of the Syriac Heritage" lines 114ff and the "Editors' Preface" lines 251ff. We might want to pull these out from the main TEI doc (along with other front and back matter). 

We should probably talk about some of those decisions soon. You could simply add some lorem ipsum in the short run, just so we can see something there.

**Comment by wsalesky** [comment]
@dlschwartz 
Okay, I made a few adjustments. Let me know if you would like any other changes. 
Also, I think we should add the Srophe logo somewhere (this one: https://github.com/srophe/srophe-eXist-app/blob/master/srophe-app/resources/img/icons/srophe-logo.png). i.e. "Powered by Srophe"

**Comment by dlschwartz** [comment]
@wsalesky 
Sorry for the delay on this. We're on spring break so I'm at home this week. I think this is an excellent start for the landing page. I agree that we should add the "Powered by Srophe" logo. I doubt we'll make any other changes before we meet with George Kiraz and get his input. I'll let you know if that changes. Thanks Winona!

**Comment by wsalesky** [comment]
Do we want the link on the Srophe logo to go to Syriaca.org or to the github app repository? (my instinct is the github repository.)

**Comment by dlschwartz** [comment]
I trust your instinct! Let's link to the github repository.
